### ISSUE TITLE
Remember Me Checkbox

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-framework-spec#18]
During the Login Process, Do we want to include a remember me token?  Here is my thought of how this would work.

If the account store tokens allow for a refresh_token, we display the checkbox.  

If the user selects the checkbox, we allow the refresh_token cookie to be set.  During the verification to see if the user is logged in (typically in middleware i believe) we check to see if the access_token is expired.  If it is, and remember me is enabled, we refresh the access_token and the user is happy.

If the user does not select remember me, we just dont set the refresh_token cookie.

**Comment by rdegges** [comment]
Hmm. I've always been against this because I feel like it's a bad user experience. This sort of thing shouldn't be left up to a user to decide, just seems silly to me. 99.99999999% of users just don't care, and unless there's a very specific security reason you DON'T want to have long sessions, you should probably always offer longer, more convenient session lengths.

**Comment by nbarbettini** [comment]
@rdegges Just to clarify, you are suggesting that "remember me" should be the default behavior, without an option presented to the user?

**Comment by rdegges** [comment]
Yes. We should, IMO, always provide a refresh cookie in the session with a reasonably long expiration. This way site access is more convenient for users.

Unless there's a very serious reason to limit session length (eg: banking websites), that should just always be the default behavior. I've always just hated those stupid remember me checkboxes because it's like: why do I have to do extra work to get behavior that should be on by default anyway? What's the purpose? Sooo annoying.

**Comment by robertjd** [comment]
I agree with @rdegges , the "remember me" experience is so varied and so mis-understood.  Until we get a customer request for such a feature, I don't see a reason to support any configuration around this.

**Comment by rdegges** [comment]
I'd like to go so far as to perma-blacklist it. Nobody should ever have a remember me box on a website, heh.

**Comment by robertjd** [comment]
Per our SDK meeting today, I am closing this issue.  Our framework integrations will not provide a "remember me" feature.  If the developer needs the functionality, we can suggest ways of achieving this with our access & refresh tokens.
