### ISSUE TITLE
Application resolution is not defined properly?

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-spec#84]
https://github.com/stormpath/stormpath-framework-spec/blob/master/configuration.md

Application resolution does not talk about loading from ENV Variables. Also I don't see these properties in web-config.yaml. 

Let's knock this out.

**Comment by nbarbettini** [comment]
That's because we're downstream of the SDK here, and it is the SDK's job to load the configuration from [all the sources](https://github.com/stormpath/stormpath-sdk-spec/blob/master/specifications/config.md#loading-order). The framework spec is just reasoning about a config object that has already been populated.

web-config.yaml only shows the `web` leaf of the `stormpath` config tree. The others could be shown for clarity I suppose.

If my understanding of this is incorrect, someone can correct me.

**Comment by omgitstom** [comment]
@nbarbettini plz update and close
